name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
     
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: satriowicaksono
          password: Gedhekcz82$
    -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: satriowicaksono/alta-store-project:latest
    
